# We use a global batch size of 1024 in stage # 3 for PLM-3B model. Please adjust batch_size as per your training setup.
# For example, one possible configuration is batch_size=4,nodes=32,gpus_per_node=8 = 4*32*8 = 1024 global batch size.

name: "plm_3b_pe_finetune"
dump_dir: "checkpoints/plm_3b_pe_finetune"
steps: 5
seed: 777
optim:
    lr: 2e-5
    warmup: 2
    lr_min_ratio: 0.01
    clip: 1.0
    weight_decay: 0.01

distributed:
    fsdp_type: full_shard
    compile: false
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    full_activation_checkpointing: true
    tp_size: 1

model:
    dim: 3072
    n_layers: 28
    n_heads: 24
    n_kv_heads: 8
    vocab_size: 128256
    ffn_dim_multiplier: 1.0
    multiple_of: 256
    norm_eps: 1e-05
    rope_theta: 500000.0
    weight_tying: true
    rope_scale_factor: 32
    high_freq_factor: 4
    max_seqlen: 4096
    freeze_language_model: true
    freeze_vision_model: false
    pooling_ratio: 2
    vision_model:
        #_target_: core.vision_encoder.pe.PE_VisionTransformer   
        image_size: 448
        patch_size: 14
        width: 1024
        layers: 50
        heads: 16
        use_cls_token: true
        use_abs_posemb: true
        mlp_ratio: 4.0
        ls_init_value: 0.1
        drop_path: 0.1
        use_ln_post: false
        pool_type: "none"
    mlp_init:
        use_gaussian: true

data:
    datamix: "unreal_dataset:1.0"
    num_workers: 4
    batch_size: 1
    image_res: 448
    max_num_tiles: 8
    max_video_frames: 32
    vision_input_type: image
    tokenizer_path: "/mnt/hitchcock/scratch/oberon/.cache/huggingface/hub/models--facebook--Perception-LM-3B/snapshots/b54263fbbb6f7590c89b9c3036a9a9d03ad8441f/tokenizer.model"
    tokenizer_name: plmchat
    conversation_format: plm_sft

profiling:
    run: false

checkpoint:
    dump:
        every: 2
        keep: 2
    init_ckpt_path: "/mnt/hitchcock/scratch/oberon/.cache/huggingface/hub/models--facebook--PE-Spatial-G14-448/snapshots/12594718a2702146ec5f73a6aef4e3cc26c28710/PE-Spatial-G14-448.pt"
    is_consolidated_model: False

logging:
    freq: 1
    level: INFO  # Available choices for logging level are: [NOTSET, DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
