name: plm_3b_pe_finetune
dump_dir: checkpoints/plm_3b_pe_finetune
seed: 777
grad_acc_steps: 1
gc_collect_freq: 1000
probe_freq: null
steps: 5
data:
  datamix: unreal_dataset:1.0
  batch_size: 1
  seed: 42
  image_res: 448
  max_num_tiles: 8
  vision_input_type: image
  num_workers: 4
  tokenizer_path: /mnt/hitchcock/scratch/oberon/.cache/huggingface/hub/models--facebook--Perception-LM-3B/snapshots/b54263fbbb6f7590c89b9c3036a9a9d03ad8441f/tokenizer.model
  tokenizer_name: plmchat
  conversation_format: plm_sft
  patch_size: null
  seq_len: null
  max_video_frames: 32
  show_first_batch: false
optim:
  lr: 2.0e-05
  weight_decay: 0.01
  epsilon: 1.0e-08
  beta1: 0.9
  beta2: 0.95
  clip: 1.0
  scheduler: cosine
  warmup: 2
  lr_min_ratio: 0.01
  cycle_length: 1.0
  cosine_theta: 1.0
  annealing_step: 10000
  decay_fraction: 0.1
  exp_factor: 0.5
model:
  dim: 3072
  n_layers: 28
  head_dim: null
  n_heads: 24
  n_kv_heads: 8
  ffn_dim_multiplier: 1.0
  multiple_of: 256
  norm_eps: 1.0e-05
  rope_theta: 500000.0
  old_context_len: 8192
  rope_scale_factor: 32
  low_freq_factor: 1
  high_freq_factor: 4
  init_base_std: null
  init_std_factor: disabled
  max_seqlen: 4096
  seed: 42
  vocab_size: 128256
  weight_tying: true
  sliding_window: null
  freeze_language_model: true
  freeze_vision_model: false
  vision_model:
    image_size: 448
    patch_size: 14
    width: 1024
    layers: 23
    heads: 16
    use_cls_token: true
    use_abs_posemb: true
    mlp_ratio: 4.0
    ls_init_value: 0.1
    drop_path: 0.1
    use_ln_post: false
    pool_type: none
  mlp_init:
    use_gaussian: true
    coeff_std: null
    no_init: false
  pooling_ratio: 2
  remove_vision_class_token: true
  attn_impl: sdpa
distributed:
  dp_shard: 1
  dp_replicate: 2
  tp_size: 1
  selective_activation_checkpointing: false
  full_activation_checkpointing: true
  compile: false
  fsdp_type: full_shard
  model_dtype: bf16
  matmul_allow_tf32: false
  detect_anomaly: false
  compile_cache_size_limit: 8
  spawn_method: forkserver
env:
  MKL_SERVICE_FORCE_INTEL: GNU
  OMP_NUM_THREADS: '1'
  MKL_NUM_THREADS: '1'
  ENABLE_INTRA_NODE_COMM: '0'
  TORCH_NCCL_AVOID_RECORD_STREAMS: '1'
  NCCL_IB_TIMEOUT: '22'
  NCCL_DEBUG: WARN
  TORCH_NCCL_ASYNC_ERROR_HANDLING: '1'
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
checkpoint:
  dump:
    every: 5
    keep: 1
  eval:
    every: 1000
    keep: 0
  path: checkpoints/plm_3b_pe_finetune/checkpoints
  init_ckpt_path: /mnt/hitchcock/scratch/oberon/.cache/huggingface/hub/models--facebook--Perception-LM-3B/snapshots/b54263fbbb6f7590c89b9c3036a9a9d03ad8441f
  vision_model_path: null
  is_consolidated_model: true
  continue_training_from_init: false
profiling:
  run: false
  trace_folder: profiling
  mem_warmup: 100
  mem_steps: 2
  profile_warmup: 102
  profile_steps: 2
logging:
  freq: 1
  level: INFO
  acc_freq: null
  wandb: null
async_eval_gpus: null
eval: null
